import 'package:get/get.dart';

class AppTranslations extends Translations {

  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "Verify" : "Verify",
          "Indentity" : "Indentity",
          "Now we need to verify your identity" : "Now we need to verify your identity",
          "Note" : "Note",
          "You are required to must upload both documents after the submit button appeared" : "You are required to must upload both documents after the submit button appeared",
          "Document Max 1 Picture Selected From Camera" : "Document Max 1 Picture Selected From Camera",
          "Document Max 2 Picture Selected From Gallery" : "Document Max 2 Picture Selected From Gallery",
          "Document Max 3 Picture Selected" : "Document Max 3 Picture Selected",
          "Take a Passport or ID to Check Your Information(Upload at Least 2 document)" : "Take a Passport or ID to Check Your Information(Upload at Least 2 document)",
          "Passport Scan" : "Passport Scan",
          "Haven't uploaded yet" : "Haven't uploaded yet",
          "Submit All" : "Submit All",
          "Selfie with your front camera to verify your identity" : "Selfie with your front camera to verify your identity",
          "Selfie" : "Selfie",
          "UPI" : "UPI",
          "Bank name" : "Bank name",
          "Account number" : "Account number",
          "Account holder name" : "Account holder name",
          "Account IFSC" : "Account IFSC",
          "Paypal" : "Paypal",
          "Withdraw Limit" : "Withdraw Limit",
          "Cancle" : "Cancle",
          "Proceed" : "Proceed",
          "Routes" : "Routes",
          "Rc Verified" : "Rc Verified",
          "Drop" : "Drop",
          "PickUp" : "PickUp",
          "FIND_LORRY" : "FIND_LORRY",
          "Rate to" : "Rate to",
          "Loads" : "Loads",
          "Load Owner Response" : "Load Owner Response",
          "Payable Amount" : "Payable Amount",
          "Accept" : "Accept",
          "Send offer" : "Send offer",
          "Waiting for offer Response" : "Waiting for offer Response",
          "UnLoad" : "UnLoad",
          "Enter Your Location" : "Enter Your Location",
          "Select Vehicle type for your load" : "Select Vehicle type for your load",
          "Available" : "Available",
          "Rejected" : "Rejected",
          "Search" : "Search",
          "Immediately Available" : "Immediately Available",
          "Select your lorry" : "Select your lorry",
          "Enter Bid Amount" : "Enter Bid Amount",
          "Bid" : "Bid",
          "Select Routes" : "Select Routes",
          "Select All" : "Select All",
          "Upload lorry document (Required at least 2 document)" : "Upload lorry document (Required at least 2 document)",
          "Lorry Document" : "Lorry Document",
          "Enter Required lorry Document" : "Enter Required lorry Document",
          "Simplify the way you find carriers.": "Simplify the way you find carriers.",
          "Don’t have an account?  ": "Don’t have an account?  ",
          "Password": "Password",
          "Uip": "Uip",
          "Pay by": "Pay by",
          "Request Date": "Request Date",
          "Proof": "Proof",
          "My Lorry's": "My Lorry's",
          "Payout Id": "Payout Id",
          "paypal": "paypal",
          "bank transfer": "bank transfer",
          "Payout Request": "Payout Request",
          "Enter your amount": "Enter your amount",
          "Request": "Request",
          "Earning": "Earning",
          "You required to contact the lorry owner for further communication": "You required to contact the lorry owner for further communication",
          "Cancellation Policy": "Cancellation Policy",
          "Contact Details": "Contact Details",
          "Enter Lorry Number": "Enter Lorry Number",
          "Transport Information": "Transport Information",
          "Skip": "Skip",
          "Add Lorry": "Add Lorry",
          "Availability Status": "Availability Status",
          "What's your expected price?": "What's your expected price?",
          "bid Now": "bid Now",
          "Post your truck and get loads": "Post your truck and get loads",
          "Find Loads": "Find Loads",
          "Attach Lorry": "Attach Lorry",
          "Near Load": "Near Load",
          "Code": "Code",
          "Already have an account?  ": "Already have an account?  ",
          "Mobile Number": "Mobile Number",
          "If A Match is Found, The System Sends An Mobile To The User's Registered Mobile Number With Instructions For Resetting Their Password.":
              "If A Match is Found, The System Sends An Mobile To The User's Registered Mobile Number With Instructions For Resetting Their Password.",
          "Forgot Password": "Forgot Password",
          "Find Lorry": "Find Lorry",
          "Post Loads": "Post Loads",
          "Faq": "Faq",
          "Refer a Friends, Get \$50": "Refer a Friends, Get \$50",
          "Get \$10 in Credit When Someone Sing Up Using Your Referal Link": "Get \$10 in Credit When Someone Sing Up Using Your Referal Link",
          "Continue With Wallet": "Continue With Wallet",
          "Wallet information": "Wallet information",
          "Enter your Price": "Enter your Price",
          "Bid Now": "Bid Now",
          "FAQ": "FAQ",
          "Reject": "Reject",
          "offer": "offer",
          "Load Tracking Status": "Load Tracking Status",
          "Accept & Pay": "Accept & Pay",
          "Lorry Owner Response": "Lorry Owner Response",
          "Load": "Load",
          "Info": "Info",
          "Total Review": "Total Review",
          "Date of Joining": "Date of Joining",
          "Route Operation": "Route Operation",
          "Enter your Feedback": "Enter your Feedback",
          "Transaction ID": "Transaction ID",
          "Payment Gateway": "Payment Gateway",
          "Payment Information": "Payment Information",
          "Bidder information": "Bidder information",
          "Bid Response": "Bid Response",
          "Total Payment": "Total Payment",
          "Sub Total": "Sub Total",
          "Payment Method": "Payment Method",
          "ACCEPT & PAY": "ACCEPT & PAY",
          "Description": "Description",
          "Bid Details": "Bid Details",
          "No": "No",
          "Yes,Continue": "Yes,Continue",
          "if you delete this bid you would not be able to view or bid on this load": "if you delete this bid you would not be able to view or bid on this load",
          "Are you want to delete bid?": "Are you want to delete bid?",
          "Your required to contact the lorry owner for further communication":
              "Your required to contact the lorry owner for further communication",
          "Material": "Material",
          "Load Process": "Load Process",
          "Tonnes": "Tonnes",
          "Date": "Date",
          "Shortly You get revert !!": "Shortly You get revert !!",
          "Name": "Name",
          "Request sent to Lorry Owner !": "Request sent to Lorry Owner !",
          "Load Details": "Load Details",
          "Load Posted !": "Load Posted !",
          "Shortly You get leads !!": "Shortly You get leads !!",
          "Drop Contact Details": "Drop Contact Details",
          "Pickup Contact Detail": "Pickup Contact Detail",
          "Hours": "Hours",
          "Number of hours": "Number of hours",
          "Not Fix": "Not Fix",
          "The number of hours visible load?":
              "The number of hours visible load?",
          "What’s your expected price?": "What’s your expected price?",
          "Post": "Post",
          "Amount": "Amount",
          "Per Tonnes": "Per Tonnes",
          "Fix": "Fix",
          "Select Vehicle": "Select Vehicle",
          "Drop Point": "Drop Point",
          "Pickup Point": "Pickup Point",
          "Next": "Next",
          "Number of Tonnes": "Number of Tonnes",
          "Material Name": "Material Name",
          "Vehicle Type": "Vehicle Type",
          "Enter Amount": "Enter Amount",
          "Operating Routes": "Operating Routes",
          "Please verify your identity First":
              "Please verify your identity First",
          "Become world’s Transporter": "Become world’s Transporter",
          "Hello..": "Hello..",
          "Confirm": "Confirm",
          "Select Payment Gateway": "Select Payment Gateway",
          "You haven't made any transaction using wallet yet":
              "You haven't made any transaction using wallet yet",
          "E-Wallet": "E-Wallet",
          "Transaction History": "Transaction History",
          "Total Earning": "Total Earning",
          "Home": "Home",
          "Wallet": "Wallet",
          "Review": "Review",
          "Terms & Conditions": "Terms & Conditions",
          "Privacy Policy": "Privacy Policy",
          "Refer to Friends": "Refer to Friends",
          "Profile": "Profile",
          "Contact Us": "Contact Us",
          "Language": "Language",
          "LogOut": "LogOut",
          "My Loads": "My Loads",
          "Booked Lorries": "Booked Lorries",
          "Enter new Password": "Enter new Password",
          "Submit": "Submit",
          "No Load Placed! Currently You Don't Have Any Loads":
              "No Load Placed! Currently You Don't Have Any Loads",
          "COMPLETED": "COMPLETED",
          "MY CURRENT LOADS": "MY CURRENT LOADS",
          "Booked Loads": "Booked Loads",
          "Full Name": "Full Name",
          "Email Address": "Email Address",
          "Seems you are new here, Let’s set up your profile.":
              "Seems you are new here, Let’s set up your profile.",
          "Getting Started!": "Getting Started!",
          "Verify Account": "Verify Account",
          "Forgot Password?": "Forgot Password?",
          "Sign up": "Sign up",
          "Resend code?": "Resend code?",
          "OTP Verification": "OTP Verification",
          "Please, enter the verification code we send to your mobile ":
              "Please, enter the verification code we send to your mobile ",
          "Login": "Login",
          "Forgot  Password?": "Forgot  Password?",
          "Let’s login for explore continues":
              "Let’s login for explore continues",
          "Welcome Back!": "Welcome Back!",
          "Get better rates on every deal.": "Get better rates on every deal.",
          "The right load for the right truck.":
              "The right load for the right truck.",
          "Search active loads by location and equipment type":
              "Search active loads by location and equipment type",
          "We match the right load to the right truck at the right price":
              "We match the right load to the right truck at the right price",
          "We offer a wide range of problem-solving products designed to help you ship more freight faster":
              "We offer a wide range of problem-solving products designed to help you ship more freight faster",
        },
        'ur_ar': {
          "Verify" : "يؤكد",
          "Indentity" : "المسافة البادئة",
          "Now we need to verify your identity" : "الآن نحن بحاجة للتحقق من هويتك",
          "Note" : "ملحوظة",
          "You are required to must upload both documents after the submit button appeared" : "يجب عليك تحميل كلا الوثيقتين بعد ظهور زر الإرسال",
          "Document Max 1 Picture Selected From Camera" : "مستند بحد أقصى 1 صورة مختارة من الكاميرا",
          "Document Max 2 Picture Selected From Gallery" : "وثيقة ماكس 2 صورة مختارة من المعرض",
          "Document Max 3 Picture Selected" : "تم تحديد المستند بحد أقصى 3 صور",
          "Take a Passport or ID to Check Your Information(Upload at Least 2 document)" : "خذ جواز سفر أو بطاقة هوية للتحقق من معلوماتك (قم بتحميل مستندين على الأقل)",
          "Passport Scan" : "مسح جواز السفر",
          "Haven't uploaded yet" : "لم يتم تحميلها بعد",
          "Submit All" : "إرسال الكل",
          "Selfie with your front camera to verify your identity" : "صورة شخصية بالكاميرا الأمامية للتحقق من هويتك",
          "Selfie" : "صورة شخصية",
          "UPI" : "واجهة الدفع الموحدة (UPI).",
          "Bank name" : "اسم البنك",
          "Account number" : "رقم الحساب",
          "Account holder name" : "اسم صاحب الحساب",
          "Account IFSC" : "حساب إفسك",
          "Paypal" : "باي بال",
          "Withdraw Limit" : "حد السحب",
          "Cancle" : "كانكل",
          "Proceed" : "يتابع",
          "Routes" : "الطرق",
          "Rc Verified" : "تم التحقق من اتفاقية روتردام",
          "Drop" : "يسقط",
          "PickUp" : "يلتقط",
          "FIND_LORRY" : "FIND_LORRY",
          "Rate to" : "معدل ل",
          "Loads" : "الأحمال",
          "Load Owner Response" : "تحميل استجابة المالك",
          "Payable Amount" : "المبلغ المستحق",
          "Accept" : "يقبل",
          "Send offer" : "إرسال العرض",
          "Waiting for offer Response" : "في انتظار الرد على العرض",
          "UnLoad" : "إلغاء التحميل",
          "Enter Your Location" : "أدخل موقعك",
          "Select Vehicle type for your load" : "حدد نوع المركبة لحمولتك",
          "Available" : "متاح",
          "Rejected" : "مرفوض",
          "Search" : "يبحث",
          "Immediately Available" : "متاح على الفور",
          "Select your lorry" : "اختر شاحنتك",
          "Enter Bid Amount" : "أدخل مبلغ العطاء",
          "Bid" : "مُنَاقَصَة",
          "Select Routes" : "حدد الطرق",
          "Select All" : "حدد الكل",
          "Upload lorry document (Required at least 2 document)" : "تحميل مستند الشاحنة (مطلوب مستندين على الأقل)",
          "Lorry Document" : "مستند الشاحنة",
          "Enter Required lorry Document" : "أدخل وثيقة الشاحنة المطلوبة",
          "Simplify the way you find carriers.": "بسّط طريقة العثور على شركات النقل.",
          "Don’t have an account?  ": "ليس لديك حساب؟",
          "Password": "كلمة المرور",
          "Uip": "UIP",
          "Pay by": "ادفع عن طريق",
          "Request Date": "تاريخ الطلب",
          "Proof": "دليل",
          "My Lorry's": "شاحنتي",
          "Payout Id": "معرف الدفع",
          "paypal": "باي بال",
          "bank transfer": "التحويل المصرفي",
          "Payout Request": "طلب الدفع",
          "Enter your amount": "أدخل المبلغ الخاص بك",
          "Request": "طلب",
          "Earning": "كسب",
          "You required to contact the lorry owner for further communication":
              "كان عليك الاتصال بمالك الشاحنة لمزيد من التواصل",
          "Cancellation Policy": "سياسة الإلغاء",
          "Contact Details": "بيانات المتصل",
          "Enter Lorry Number": "أدخل رقم الشاحنة",
          "Transport Information": "معلومات النقل",
          "Skip": "يتخطى",
          "Add Lorry": "أضف شاحنة",
          "Availability Status": "توافر الحالة",
          "What's your expected price?": "ما هو سعرك المتوقع ؟",
          "bid Now": "محاولة الآن",
          "Post your truck and get loads": "أضف شاحنتك واحصل على الأحمال",
          "Find Loads": "البحث عن الأحمال",
          "Attach Lorry": "إرفاق شاحنة",
          "Near Load": "بالقرب من التحميل",
          "Code": "شفرة",
          "Already have an account?  ": "هل لديك حساب؟",
          "Mobile Number": "رقم الهاتف المحمول",
          "If A Match is Found, The System Sends An Mobile To The User's Registered Mobile Number With Instructions For Resetting Their Password.":
              "إذا تم العثور على تطابق، يرسل النظام هاتفًا محمولاً إلى رقم الهاتف المحمول المسجل للمستخدم مع تعليمات إعادة تعيين كلمة المرور الخاصة به.",
          "Forgot Password": "هل نسيت كلمة السر",
          "Find Lorry": "ابحث عن شاحنة",
          "Post Loads": "نشر الأحمال",
          "Faq": "التعليمات",
          "Continue With Wallet": "تواصل مع المحفظة",
          "Wallet information": "معلومات المحفظة",
          "Enter your Price": "أدخل السعر الخاص بك",
          "Bid Now": "المزايدة الآن",
          "FAQ": "التعليمات",
          "Reject": "يرفض",
          "offer": "يعرض",
          "Load Tracking Status": "حالة تتبع التحميل",
          "Accept & Pay": "قبول والدفع",
          "Lorry Owner Response": "رد مالك الشاحنة",
          "Load": "حمولة",
          "Info": "معلومات",
          "Total Review": "المراجعة الإجمالية",
          "Date of Joining": "تاريخ الإنضمام",
          "Route Operation": "عملية الطريق",
          "Enter your Feedback": "أدخل ملاحظاتك",
          "Transaction ID": "رقم المعاملة",
          "Payment Gateway": "بوابة الدفع",
          "Payment Information": "معلومات الدفع",
          "Bidder information": "معلومات مقدم العرض",
          "Bid Response": "استجابة العطاء",
          "Total Payment": "المبلغ الإجمالي",
          "Sub Total": "المجموع الفرعي",
          "Payment Method": "طريقة الدفع او السداد",
          "ACCEPT & PAY": "قبول والدفع",
          "Description": "وصف",
          "Bid Details": "تفاصيل العطاء",
          "No": "لا",
          "Yes,Continue": "نعم، استمر",
          "if you delete this bid you would not be able to view or bid on this load":
              "إذا قمت بحذف عرض الأسعار هذا، فلن تتمكن من عرض هذا التحميل أو تقديم عرض عليه",
          "Are you want to delete bid?": "هل تريد حذف العطاء؟",
          "Your required to contact the lorry owner for further communication":
              "مطلوب منك الاتصال بمالك الشاحنة لمزيد من التواصل",
          "Material": "مادة",
          "Load Process": "عملية التحميل",
          "Tonnes": "طن",
          "Date": "تاريخ",
          "Shortly You get revert !!": "وسرعان ما ستعود!!",
          "Name": "اسم",
          "Request sent to Lorry Owner !": "تم إرسال الطلب إلى مالك الشاحنة!",
          "Load Details": "تفاصيل التحميل",
          "Load Posted !": "تحميل تم النشر!",
          "Shortly You get leads !!": "قريبا تحصل على عملاء محتملين !!",
          "Drop Contact Details": "إسقاط تفاصيل الاتصال",
          "Pickup Contact Detail": "تفاصيل الاتصال بيك اب",
          "Hours": "ساعات",
          "Number of hours": "عدد الساعات",
          "Not Fix": "غير ثابت",
          "The number of hours visible load?": "عدد ساعات الحمل المرئية؟",
          "What’s your expected price?": "ما هو سعرك المتوقع ؟",
          "Post": "بريد",
          "Amount": "كمية",
          "Per Tonnes": "لكل طن",
          "Fix": "يصلح",
          "Select Vehicle": "اختر مركبة",
          "Drop Point": "نقطة الإسقاط",
          "Pickup Point": "نقطة الالتقاط",
          "Next": "التالي",
          "Number of Tonnes": "عدد الأطنان",
          "Material Name": "اسم المادة",
          "Vehicle Type": "نوع السيارة",
          "Enter Amount": "أدخل المبلغ",
          "Operating Routes": "طرق التشغيل",
          "Please verify your identity First": "يرجى التحقق من هويتك أولا",
          "Become world’s Transporter": "تصبح نقل العالم",
          "Hello..": "مرحبًا..",
          "Confirm": "يتأكد",
          "Select Payment Gateway": "حدد بوابة الدفع",
          "You haven't made any transaction using wallet yet":
              "لم تقم بإجراء أي معاملة باستخدام المحفظة حتى الآن",
          "E-Wallet": "المحفظة الإلكترونية",
          "Transaction History": "تاريخ المعاملات",
          "Total Earning": "مجموع الأرباح",
          "Home": "بيت",
          "Wallet": "محفظة",
          "Review": "مراجعة",
          "Terms & Conditions": "البنود و الظروف",
          "Privacy Policy": "سياسة الخصوصية",
          "Refer to Friends": "الرجوع إلى الأصدقاء",
          "Profile": "حساب تعريفي",
          "Contact Us": "اتصل بنا",
          "Language": "لغة",
          "LogOut": "تسجيل خروج",
          "My Loads": "أحمالي",
          "Booked Lorries": "الشاحنات المحجوزة",
          "Enter new Password": "أدخل كلمة المرور الجديدة",
          "Submit": "يُقدِّم",
          "No Load Placed! Currently You Don't Have Any Loads":
              "لم يتم وضع أي تحميل! حاليا ليس لديك أي أحمال",
          "COMPLETED": "مكتمل",
          "MY CURRENT LOADS": "أحمالي الحالية",
          "Booked Loads": "الأحمال المحجوزة",
          "Full Name": "الاسم الكامل",
          "Email Address": "عنوان البريد الإلكتروني",
          "Seems you are new here, Let’s set up your profile.":
              "يبدو أنك جديد هنا، فلنقم بإعداد ملف التعريف الخاص بك.",
          "Getting Started!": "ابدء!",
          "Verify Account": "التحقق من الحساب",
          "Forgot Password?": "هل نسيت كلمة السر؟",
          "Sign up": "اشتراك",
          "Resend code?": "أعد إرسال الرمز؟",
          "OTP Verification": "التحقق من OTP",
          "Please, enter the verification code we send to your mobile ":
              "من فضلك قم بإدخال رمز التحقق الذي أرسلناه إلى هاتفك المحمول",
          "Login": "تسجيل الدخول",
          "Forgot  Password?": "هل نسيت كلمة السر؟",
          "Let’s login for explore continues":
              "دعنا نسجل الدخول للاستكشاف المستمر",
          "Welcome Back!": "مرحبًا بعودتك!",
          "Get better rates on every deal.": "احصل على أسعار أفضل على كل صفقة.",
          "The right load for the right truck.":
              "الحمولة المناسبة للشاحنة المناسبة.",
          "Search active loads by location and equipment type":
              "بحث الأحمال النشطة حسب الموقع ونوع المعدات",
          "We match the right load to the right truck at the right price":
              "نحن نطابق الحمولة المناسبة بالشاحنة المناسبة بالسعر المناسب",
          "We offer a wide range of problem-solving products designed to help you ship more freight faster":
              "نحن نقدم مجموعة واسعة من منتجات حل المشكلات المصممة لمساعدتك على شحن المزيد من البضائع بشكل أسرع",
        },
        'af_ge': {
          "Verify" : "Verifieer",
          "Indentity" : "Indentiteit",
          "Now we need to verify your identity" : "Nou moet ons jou identiteit verifieer",
          "Note" : "Let wel",
          "You are required to must upload both documents after the submit button appeared" : "Daar word van u verwag om beide dokumente op te laai nadat die indien-knoppie verskyn het",
          "Document Max 1 Picture Selected From Camera" : "Dokument Maks. 1 prent gekies uit kamera",
          "Document Max 2 Picture Selected From Gallery" : "Dokument Max 2 Prent gekies uit Galery",
          "Document Max 3 Picture Selected" : "Dokument Maks. 3 Prent gekies",
          "Take a Passport or ID to Check Your Information(Upload at Least 2 document)" : "Neem 'n paspoort of ID om jou inligting na te gaan (laai ten minste 2 dokumente op)",
          "Passport Scan" : "Paspoort skandering",
          "Haven't uploaded yet" : "Het nog nie opgelaai nie",
          "Submit All" : "Dien alles in",
          "Selfie with your front camera to verify your identity" : "Selfie met jou voorste kamera om jou identiteit te verifieer",
          "Selfie" : "Selfie",
          "UPI" : "UPI",
          "Bank name" : "Bank naam",
          "Account number" : "Rekeningnommer",
          "Account holder name" : "Rekeninghouer se naam",
          "Account IFSC" : "Rekening IFSC",
          "Paypal" : "Paypal",
          "Withdraw Limit" : "Onttrek limiet",
          "Cancle" : "Kankel",
          "Proceed" : "Gaan voort",
          "Routes" : "Roetes",
          "Rc Verified" : "Rc geverifieer",
          "Drop" : "Laat val",
          "PickUp" : "Optel",
          "FIND_LORRY" : "FIND_LORRY",
          "Rate to" : "Beoordeel na",
          "Loads" : "Vragte",
          "Load Owner Response" : "Laai Eienaarreaksie",
          "Payable Amount" : "Betaalbare bedrag",
          "Accept" : "Aanvaar",
          "Send offer" : "Stuur aanbod",
          "Waiting for offer Response" : "Wag vir aanbodreaksie",
          "UnLoad" : "Laai af",
          "Enter Your Location" : "Voer jou ligging in",
          "Select Vehicle type for your load" : "Kies Voertuigtipe vir jou vrag",
          "Available" : "Beskikbaar",
          "Rejected" : "Verwerp",
          "Search" : "Soek",
          "Immediately Available" : "Dadelik Beskikbaar",
          "Select your lorry" : "Kies jou vragmotor",
          "Enter Bid Amount" : "Voer bodbedrag in",
          "Bid" : "Bied",
          "Select Routes" : "Kies Roetes",
          "Select All" : "Kies Alles",
          "Upload lorry document (Required at least 2 document)" : "Laai vragmotordokument op (ten minste 2 dokumente benodig)",
          "Lorry Document" : "Vragmotor dokument",
          "Enter Required lorry Document" : "Voer Vereiste vragmotordokument in",
          "Simplify the way you find carriers.":
              "Vereenvoudig die manier waarop jy draers vind.",
          "Don’t have an account?  ": "Het jy nie 'n rekening nie?",
          "Password": "Wagwoord",
          "Uip": "uip",
          "Pay by": "Betaal deur",
          "Request Date": "versoekdatum",
          "Proof": "Bewys",
          "My Lorry's": "My lorrie s'n",
          "Payout Id": "Uitbetaling ID",
          "paypal": "paypal",
          "bank transfer": "bankoorplasing",
          "Payout Request": "Uitbetaling Versoek",
          "Enter your amount": "Voer jou bedrag in",
          "Request": "versoek",
          "Earning": "Inkomste",
          "You required to contact the lorry owner for further communication":
              "U moes die eienaar van die vragmotor kontak vir verdere kommunikasie",
          "Cancellation Policy": "Kansellasie beleid",
          "Contact Details": "Kontakbesonderhede",
          "Enter Lorry Number": "Voer vragmotornommer in",
          "Transport Information": "Vervoer inligting",
          "Skip": "huppel",
          "Add Lorry": "Voeg Lorry by",
          "Availability Status": "Beskikbaarheid Status",
          "What's your expected price?": "Wat is jou verwagte prys?",
          "bid Now": "bied nou",
          "Post your truck and get loads": "Plaas jou trok en kry vragte",
          "Find Loads": "Vind vragte",
          "Attach Lorry": "Heg Lorrie aan",
          "Near Load": "Naby vrag",
          "Code": "kode",
          "Already have an account?  ": "Reeds 'n rekening?",
          "Mobile Number": "Selfoon nommer",
          "If A Match is Found, The System Sends An Mobile To The User's Registered Mobile Number With Instructions For Resetting Their Password.":
              "As 'n passing gevind word, stuur die stelsel 'n selfoon na die gebruiker se geregistreerde selfoonnommer met instruksies om hul wagwoord terug te stel.",
          "Forgot Password": "Wagwoord vergeet",
          "Find Lorry": "Soek vir Lorry",
          "Post Loads": "Plaas vragte",
          "Faq": "Gereelde vrae",
          "Continue With Wallet": "Gaan voort met Wallet",
          "Wallet information": "Beursie inligting",
          "Enter your Price": "Voer jou prys in",
          "Bid Now": "Bied nou",
          "FAQ": "Gereelde vrae",
          "Reject": "verwerp",
          "offer": "bied",
          "Load Tracking Status": "Laai dopstatus",
          "Accept & Pay": "Aanvaar & Betaal",
          "Lorry Owner Response": "Vragmotor-eienaar se reaksie",
          "Load": "laai",
          "Info": "Inligting",
          "Total Review": "Totale resensie",
          "Date of Joining": "Datum van aansluiting",
          "Route Operation": "Roete Operasie",
          "Enter your Feedback": "Voer jou terugvoer in",
          "Transaction ID": "Transaksie ID",
          "Payment Gateway": "Betalingspoort",
          "Payment Information": "Betaling Inligting",
          "Bidder information": "Bieër inligting",
          "Bid Response": "Bied reaksie",
          "Total Payment": "Totale betaling",
          "Sub Total": "Subtotaal",
          "Payment Method": "Betalings metode",
          "ACCEPT & PAY": "AANVAAR EN BETAAL",
          "Description": "Beskrywing",
          "Bid Details": "Bied besonderhede",
          "No": "geen",
          "Yes,Continue": "Ja, gaan voort",
          "if you delete this bid you would not be able to view or bid on this load":
              "as jy hierdie bod uitvee, sal jy nie hierdie vrag kan sien of daarop kan bie nie",
          "Are you want to delete bid?": "Wil jy bod uitvee?",
          "Your required to contact the lorry owner for further communication":
              "U moet die eienaar van die vragmotor kontak vir verdere kommunikasie",
          "Material": "Materiaal",
          "Load Process": "Laai proses",
          "Tonnes": "toon",
          "Date": "datum",
          "Shortly You get revert !!": "Binnekort kry jy terug!!",
          "Name": "Naam",
          "Request sent to Lorry Owner !":
              "Versoek gestuur aan vragmotor eienaar!",
          "Load Details": "Laai Besonderhede",
          "Load Posted !": "Laai geplaas!",
          "Shortly You get leads !!": "Binnekort kry jy leidrade!!",
          "Drop Contact Details": "Los kontakbesonderhede",
          "Pickup Contact Detail": "Afhaal kontakbesonderhede",
          "Hours": "Ure",
          "Number of hours": "Aantal ure",
          "Not Fix": "Nie reg",
          "The number of hours visible load?": "Die aantal ure sigbare vrag?",
          "What’s your expected price?": "Wat is jou verwagte prys?",
          "Post": "Plasings",
          "Amount": "Bedrag",
          "Per Tonnes": "Per ton",
          "Fix": "vasgestel",
          "Select Vehicle": "Kies Voertuig",
          "Drop Point": "Drop Point",
          "Pickup Point": "Optelpunt",
          "Next": "Volgende",
          "Number of Tonnes": "Aantal ton",
          "Material Name": "Materiaal Naam",
          "Vehicle Type": "Voertuig tipe",
          "Enter Amount": "Voer Bedrag in",
          "Operating Routes": "Bedryfsroetes",
          "Please verify your identity First":
              "Verifieer asseblief eers jou identiteit",
          "Become world’s Transporter": "Word die wêreld se vervoerder",
          "Hello..": "Hallo..",
          "Confirm": "bevestig",
          "Select Payment Gateway": "Kies Payment Gateway",
          "You haven't made any transaction using wallet yet":
              "Jy het nog geen transaksie met beursie gemaak nie",
          "E-Wallet": "E-beursie",
          "Transaction History": "Transaksiegeskiedenis",
          "Total Earning": "Totale verdienste",
          "Home": "Tuis",
          "Wallet": "beursie",
          "Review": "Resensies",
          "Terms & Conditions": "terme en voorwaardes",
          "Privacy Policy": "Privaatheidsbeleid",
          "Refer to Friends": "Verwys na Vriende",
          "Profile": "profiel",
          "Contact Us": "Kontak Ons",
          "Language": "Taal",
          "LogOut": "Teken uit",
          "My Loads": "My vragte",
          "Booked Lorries": "Vragmotors bespreek",
          "Enter new Password": "Voer nuwe wagwoord in",
          "Submit": "Indien",
          "No Load Placed! Currently You Don't Have Any Loads":
              "Geen vrag geplaas nie! Tans het jy geen vragte nie",
          "COMPLETED": "VOLTOOI",
          "MY CURRENT LOADS": "MY HUIDIGE LADINGS",
          "Booked Loads": "Bespreek Vragte",
          "Full Name": "Volle naam",
          "Email Address": "E-pos adres",
          "Seems you are new here, Let’s set up your profile.":
              "Dit lyk of jy nuut hier is, kom ons stel jou profiel op.",
          "Getting Started!": "Aan die gang kom!",
          "Verify Account": "Verifieer rekening",
          "Forgot Password?": "Wagwoord vergeet?",
          "Sign up": "Teken aan",
          "Resend code?": "Herstuur kode?",
          "OTP Verification": "OTP-verifikasie",
          "Please, enter the verification code we send to your mobile ":
              "Voer asseblief die verifikasiekode in wat ons na jou selfoon stuur",
          "Login": "Teken aan",
          "Forgot  Password?": "Wagwoord vergeet?",
          "Let’s login for explore continues":
              "Kom ons meld aan vir verken gaan voort",
          "Welcome Back!": "Welkom terug!",
          "Get better rates on every deal.":
              "Kry beter tariewe op elke transaksie.",
          "The right load for the right truck.":
              "Die regte vrag vir die regte vragmotor.",
          "Search active loads by location and equipment type":
              "Soek aktiewe vragte volgens ligging en tipe toerusting",
          "We match the right load to the right truck at the right price":
              "Ons pas die regte vrag by die regte vragmotor teen die regte prys",
          "We offer a wide range of problem-solving products designed to help you ship more freight faster":
              "Ons bied 'n wye reeks probleemoplossingsprodukte wat ontwerp is om jou te help om meer vrag vinniger te stuur",
        },
        'be_ge': {
          "Verify" : "যাচাই করুন",
          "Indentity" : "পরিচয়",
          "Now we need to verify your identity" : "এখন আমাদের আপনার পরিচয় যাচাই করতে হবে",
          "Note" : "দ্রষ্টব্য",
          "You are required to must upload both documents after the submit button appeared" : "জমা বোতামটি উপস্থিত হওয়ার পরে আপনাকে অবশ্যই উভয় নথি আপলোড করতে হবে",
          "Document Max 1 Picture Selected From Camera" : "নথি সর্বোচ্চ 1 ছবি ক্যামেরা থেকে নির্বাচিত",
          "Document Max 2 Picture Selected From Gallery" : "ডকুমেন্ট ম্যাক্স 2 ছবি গ্যালারি থেকে নির্বাচিত",
          "Document Max 3 Picture Selected" : "নথি সর্বাধিক 3 ছবি নির্বাচিত",
          "Take a Passport or ID to Check Your Information(Upload at Least 2 document)" : "আপনার তথ্য পরীক্ষা করতে একটি পাসপোর্ট বা আইডি নিন (কমপক্ষে 2 নথি আপলোড করুন)",
          "Passport Scan" : "পাসপোর্ট স্ক্যান",
          "Haven't uploaded yet" : "এখনো আপলোড করিনি",
          "Submit All" : "সব জমা দিন",
          "Selfie with your front camera to verify your identity" : "আপনার পরিচয় যাচাই করতে আপনার সামনের ক্যামেরা দিয়ে সেলফি নিন",
          "Selfie" : "সেলফি",
          "UPI" : "ইউপিআই",
          "Bank name" : "ব্যাঙ্কের নাম",
          "Account number" : "অ্যাকাউন্ট নম্বর",
          "Account holder name" : "অ্যাকাউন্টধারীর নাম",
          "Account IFSC" : "IFSC অ্যাকাউন্ট",
          "Paypal" : "পেপ্যাল",
          "Withdraw Limit" : "প্রত্যাহার সীমা",
          "Cancle" : "ক্যানকেল",
          "Proceed" : "এগিয়ে যান",
          "Routes" : "রুট",
          "Rc Verified" : "আরসি যাচাই করা হয়েছে",
          "Drop" : "ড্রপ",
          "PickUp" : "পিকআপ",
          "FIND_LORRY" : "FIND_LORRY",
          "Rate to" : "রেট",
          "Loads" : "লোড",
          "Load Owner Response" : "লোড মালিক প্রতিক্রিয়া",
          "Payable Amount" : "প্রদেয় পরিমাণ",
          "Accept" : "গ্রহণ করুন",
          "Send offer" : "অফার পাঠান",
          "Waiting for offer Response" : "প্রস্তাব প্রতিক্রিয়া জন্য অপেক্ষা",
          "UnLoad" : "আনলোড করুন",
          "Enter Your Location" : "আপনার অবস্থান লিখুন",
          "Select Vehicle type for your load" : "আপনার লোডের জন্য গাড়ির ধরন নির্বাচন করুন",
          "Available" : "পাওয়া যায়",
          "Rejected" : "প্রত্যাখ্যাত",
          "Search" : "অনুসন্ধান করুন",
          "Immediately Available" : "অবিলম্বে উপলব্ধ",
          "Select your lorry" : "আপনার লরি নির্বাচন করুন",
          "Enter Bid Amount" : "বিডের পরিমাণ লিখুন",
          "Bid" : "বিড",
          "Select Routes" : "রুট নির্বাচন করুন",
          "Select All" : "সব নির্বাচন করুন",
          "Upload lorry document (Required at least 2 document)" : "লরি ডকুমেন্ট আপলোড করুন (কমপক্ষে ২টি ডকুমেন্ট প্রয়োজন)",
          "Lorry Document" : "লরি ডকুমেন্ট",
          "Enter Required lorry Document" : "প্রয়োজনীয় লরি ডকুমেন্ট লিখুন",
          "Simplify the way you find carriers.":
              "আপনি যেভাবে ক্যারিয়ার খুঁজে পান তা সহজ করুন।",
          "Don’t have an account?  ": "একটি অ্যাকাউন্ট নেই?",
          "Password": "পাসওয়ার্ড",
          "Uip": "uip",
          "Pay by": "দ্বারা বেতন",
          "Request Date": "অনুরোধ তারিখ",
          "Proof": "প্রমাণ",
          "My Lorry's": "আমার লরি",
          "Payout Id": "পেআউট আইডি",
          "paypal": "পেপ্যাল",
          "bank transfer": "ব্যাংক লেনদেন",
          "Payout Request": "পেআউট অনুরোধ",
          "Enter your amount": "আপনার পরিমাণ লিখুন",
          "Request": "অনুরোধ",
          "Earning": "আয়",
          "You required to contact the lorry owner for further communication":
              "আরও যোগাযোগের জন্য আপনাকে লরি মালিকের সাথে যোগাযোগ করতে হবে",
          "Cancellation Policy": "বাতিলকরণ নীতি",
          "Contact Details": "যোগাযোগের ঠিকানা",
          "Enter Lorry Number": "লরি নম্বর লিখুন",
          "Transport Information": "পরিবহন তথ্য",
          "Skip": "এড়িয়ে যান",
          "Add Lorry": "লরি যোগ করুন",
          "Availability Status": "সহজলভ্যতা স্থিতি",
          "What's your expected price?": "আপনার প্রত্যাশিত মূল্য কি?",
          "bid Now": "আঘাত কর",
          "Post your truck and get loads":
              "আপনার ট্রাক পোস্ট করুন এবং লোড পেতে",
          "Find Loads": "লোড খুঁজুন",
          "Attach Lorry": "লরি সংযুক্ত করুন",
          "Near Load": "লোডের কাছাকাছি",
          "Code": "কোড",
          "Already have an account?  ": "ইতিমধ্যে একটি সদস্যপদ আছে?",
          "Mobile Number": "মোবাইল নম্বর",
          "If A Match is Found, The System Sends An Mobile To The User's Registered Mobile Number With Instructions For Resetting Their Password.":
              "যদি একটি মিল পাওয়া যায়, সিস্টেমটি ব্যবহারকারীর নিবন্ধিত মোবাইল নম্বরে তাদের পাসওয়ার্ড রিসেট করার নির্দেশনা সহ একটি মোবাইল পাঠায়।",
          "Forgot Password": "পাসওয়ার্ড ভুলে গেছেন",
          "Find Lorry": "লরি খুঁজুন",
          "Post Loads": "পোস্ট লোড",
          "Faq": "প্রশ্ন",
          "Continue With Wallet": "ওয়ালেট দিয়ে চালিয়ে যান",
          "Wallet information": "ওয়ালেট তথ্য",
          "Enter your Price": "আপনার মূল্য লিখুন",
          "Bid Now": "আঘাত কর",
          "FAQ": "FAQ",
          "Reject": "প্রত্যাখ্যান",
          "offer": "অফার",
          "Load Tracking Status": "লোড ট্র্যাকিং অবস্থা",
          "Accept & Pay": "গ্রহণ করুন এবং অর্থ প্রদান করুন",
          "Lorry Owner Response": "লরি মালিকের প্রতিক্রিয়া",
          "Load": "বোঝা",
          "Info": "তথ্য",
          "Total Review": "মোট পর্যালোচনা",
          "Date of Joining": "যোগদানের তারিখ",
          "Route Operation": "রুট অপারেশন",
          "Enter your Feedback": "আপনার প্রতিক্রিয়া লিখুন",
          "Transaction ID": "লেনদেন নাম্বার",
          "Payment Gateway": "পেমেন্ট গেটওয়ে",
          "Payment Information": "পেমেন্ট তথ্য",
          "Bidder information": "দরদাতার তথ্য",
          "Bid Response": "বিড রেসপন্স",
          "Total Payment": "মোট পরিশোধ",
          "Sub Total": "উপ মোট",
          "Payment Method": "মূল্যপরিশোধ পদ্ধতি",
          "ACCEPT & PAY": "গ্রহণ করুন এবং অর্থ প্রদান করুন",
          "Description": "বর্ণনা",
          "Bid Details": "বিডের বিবরণ",
          "No": "না",
          "Yes,Continue": "হ্যাঁ, চালিয়ে যান",
          "if you delete this bid you would not be able to view or bid on this load":
              "আপনি এই বিড মুছে ফেললে আপনি এই লোড দেখতে বা বিড করতে সক্ষম হবে না",
          "Are you want to delete bid?": "আপনি বিড মুছে ফেলতে চান?",
          "Your required to contact the lorry owner for further communication":
              "আপনার আরও যোগাযোগের জন্য লরি মালিকের সাথে যোগাযোগ করতে হবে",
          "Material": "উপকরণ",
          "Load Process": "লোড প্রক্রিয়া",
          "Tonnes": "টোন",
          "Date": "তারিখ",
          "Shortly You get revert !!": "শীঘ্রই আপনি ফিরে পাবেন!!",
          "Name": "নাম",
          "Request sent to Lorry Owner !":
              "লরি মালিকের কাছে অনুরোধ পাঠানো হয়েছে!",
          "Load Details": "লোড বিবরণ",
          "Load Posted !": "লোড পোস্ট!",
          "Shortly You get leads !!": "শীঘ্রই আপনি নেতৃত্ব পাবেন!!",
          "Drop Contact Details": "যোগাযোগের বিবরণ বাদ দিন",
          "Pickup Contact Detail": "যোগাযোগ বিশদ পিক আপ",
          "Hours": "ঘন্টার",
          "Number of hours": "ঘন্টার সংখ্যা",
          "Not Fix": "অনির্ধারিত",
          "The number of hours visible load?": "লোড দৃশ্যমান ঘন্টা সংখ্যা?",
          "What’s your expected price?": "আপনার প্রত্যাশিত মূল্য কি?",
          "Post": "পোস্ট",
          "Amount": "পরিমাণ",
          "Per Tonnes": "প্রতি টন",
          "Fix": "স্থির",
          "Select Vehicle": "যানবাহন নির্বাচন করুন",
          "Drop Point": "ড্রপ পয়েন্ট",
          "Pickup Point": "সংগ্রহের স্থান",
          "Next": "পরবর্তী",
          "Number of Tonnes": "টন সংখ্যা",
          "Material Name": "উপাদানের নাম",
          "Vehicle Type": "গাড়ির ধরন",
          "Enter Amount": "পরিমান লিখুন",
          "Operating Routes": "অপারেটিং রুট",
          "Please verify your identity First": "আগে আপনার পরিচয় যাচাই করুন",
          "Become world’s Transporter": "বিশ্বের পরিবহণকারী হয়ে উঠুন",
          "Hello..": "হ্যালো..",
          "Confirm": "নিশ্চিত করুন",
          "Select Payment Gateway": "পেমেন্ট গেটওয়ে নির্বাচন করুন",
          "You haven't made any transaction using wallet yet":
              "আপনি এখনও ওয়ালেট ব্যবহার করে কোনো লেনদেন করেননি",
          "E-Wallet": "ই-ওয়ালেট",
          "Transaction History": "আপনি কি আমার সাথে কি করতে চান",
          "Total Earning": "মোট উপার্জন",
          "Home": "বাড়ি",
          "Wallet": "মানিব্যাগ",
          "Review": "রিভিউ",
          "Terms & Conditions": "শর্তাবলী",
          "Privacy Policy": "গোপনীয়তা নীতি",
          "Refer to Friends": "বন্ধুদের পড়ুন",
          "Profile": "প্রোফাইল",
          "Contact Us": "যোগাযোগ করুন",
          "Language": "ভাষা",
          "LogOut": "প্রস্থান",
          "My Loads": "আমার লোড",
          "Booked Lorries": "বুক করা লরি",
          "Enter new Password": "নতুন পাসওয়ার্ড লিখুন",
          "Submit": "জমা দিন",
          "No Load Placed! Currently You Don't Have Any Loads":
              "কোন লোড স্থাপন করা হয়েছে! বর্তমানে আপনার কোন লোড নেই",
          "COMPLETED": "সম্পূর্ণ",
          "MY CURRENT LOADS": "আমার বর্তমান লোড",
          "Booked Loads": "বুক করা লোড",
          "Full Name": "পুরো নাম",
          "Email Address": "ইমেইল ঠিকানা",
          "Seems you are new here, Let’s set up your profile.":
              "মনে হচ্ছে আপনি এখানে নতুন, আপনার প্রোফাইল সেট আপ করা যাক.",
          "Getting Started!": "শুরু হচ্ছে!",
          "Verify Account": "এ্যাকাউন্ট নিশ্চিতকরণ",
          "Forgot Password?": "পাসওয়ার্ড ভুলে গেছেন?",
          "Sign up": "নিবন্ধন করুন",
          "Resend code?": "পুনরায় পাঠানো কোড?",
          "OTP Verification": "OTP যাচাইকরণ",
          "Please, enter the verification code we send to your mobile ":
              "অনুগ্রহ করে, আমরা আপনার মোবাইলে যে যাচাইকরণ কোডটি পাঠাই তা লিখুন",
          "Login": "প্রবেশ করুন",
          "Forgot  Password?": "পাসওয়ার্ড ভুলে গেছেন?",
          "Let’s login for explore continues":
              "অন্বেষণ অব্যাহত জন্য লগইন করা যাক",
          "Welcome Back!": "ফিরে আসার জন্য স্বাগতম!",
          "Get better rates on every deal.":
              "প্রতিটি চুক্তিতে আরও ভাল হার পান।",
          "The right load for the right truck.": "সঠিক ট্রাকের জন্য সঠিক লোড।",
          "Search active loads by location and equipment type":
              "অবস্থান এবং সরঞ্জামের ধরন দ্বারা সক্রিয় লোড খুঁজুন",
          "We match the right load to the right truck at the right price":
              "আমরা সঠিক দামে সঠিক ট্রাকে সঠিক লোড মেলে",
          "We offer a wide range of problem-solving products designed to help you ship more freight faster":
              "আমরা আপনাকে আরও দ্রুত মালবাহী জাহাজে সহায়তা করার জন্য ডিজাইন করা সমস্যা-সমাধান পণ্যগুলির একটি বিস্তৃত পরিসর অফার করি",
        },
        'sp_GE': {
          "Verify" : "Verificar",
          "Indentity" : "Identidad",
          "Now we need to verify your identity" : "Ahora necesitamos verificar tu identidad.",
          "Note" : "Nota",
          "You are required to must upload both documents after the submit button appeared" : "Debe cargar ambos documentos después de que aparezca el botón Enviar.",
          "Document Max 1 Picture Selected From Camera" : "Documento Máximo 1 imagen seleccionada de la cámara",
          "Document Max 2 Picture Selected From Gallery" : "Documento máximo 2 imágenes seleccionadas de la galería",
          "Document Max 3 Picture Selected" : "Documento Máximo 3 imágenes seleccionadas",
          "Take a Passport or ID to Check Your Information(Upload at Least 2 document)" : "Lleve un pasaporte o identificación para verificar su información (cargue al menos 2 documentos)",
          "Passport Scan" : "Escaneo de pasaporte",
          "Haven't uploaded yet" : "Aún no lo he subido",
          "Submit All" : "Enviar todo",
          "Selfie with your front camera to verify your identity" : "Selfie con tu cámara frontal para verificar tu identidad",
          "Selfie" : "autofoto",
          "UPI" : "UPI",
          "Bank name" : "nombre del banco",
          "Account number" : "Número de cuenta",
          "Account holder name" : "Nombre del titular de la cuenta",
          "Account IFSC" : "Cuenta IFSC",
          "Paypal" : "PayPal",
          "Withdraw Limit" : "Límite de retiro",
          "Cancle" : "Cancelar",
          "Proceed" : "Proceder",
          "Routes" : "Rutas",
          "Rc Verified" : "Rc Verificado",
          "Drop" : "Gota",
          "PickUp" : "Levantar",
          "FIND_LORRY" : "ENCONTRAR_LORRY",
          "Rate to" : "Tarifa a",
          "Loads" : "Cargas",
          "Load Owner Response" : "Cargar respuesta del propietario",
          "Payable Amount" : "Monto a pagar",
          "Accept" : "Aceptar",
          "Send offer" : "Enviar oferta",
          "Waiting for offer Response" : "Esperando oferta Respuesta",
          "UnLoad" : "Descargar",
          "Enter Your Location" : "Ingrese su ubicación",
          "Select Vehicle type for your load" : "Seleccione el tipo de vehículo para su carga",
          "Available" : "Disponible",
          "Rejected" : "Rechazado",
          "Search" : "Buscar",
          "Immediately Available" : "Disponible inmediatamente",
          "Select your lorry" : "Selecciona tu camión",
          "Enter Bid Amount" : "Ingrese el monto de la oferta",
          "Bid" : "Licitación",
          "Select Routes" : "Seleccionar rutas",
          "Select All" : "Seleccionar todo",
          "Upload lorry document (Required at least 2 document)" : "Subir documento de camión (Se requieren al menos 2 documentos)",
          "Lorry Document" : "Documento de camión",
          "Enter Required lorry Document" : "Introduzca el documento de camión requerido",
          "Simplify the way you find carriers.":
              "Simplifique la forma de encontrar transportistas.",
          "Don’t have an account?  ": "¿No tienes una cuenta?",
          "Password": "Contraseña",
          "Uip": "UIP",
          "Pay by": "Pagado por",
          "Request Date": "Fecha de solicitud",
          "Proof": "Prueba",
          "My Lorry's": "mi camión",
          "Payout Id": "ID de pago",
          "paypal": "paypal",
          "bank transfer": "transferencia bancaria",
          "Payout Request": "Solicitud de pago",
          "Enter your amount": "Introduce tu importe",
          "Request": "Pedido",
          "Earning": "Ganador",
          "You required to contact the lorry owner for further communication":
              "Debe comunicarse con el propietario del camión para mayor comunicación.",
          "Cancellation Policy": "Política de cancelación",
          "Contact Details": "Detalles de contacto",
          "Enter Lorry Number": "Introduzca el número de camión",
          "Transport Information": "Información de transporte",
          "Skip": "Saltar",
          "Add Lorry": "Añadir camión",
          "Availability Status": "Estado de Disponibilidad",
          "What's your expected price?": "¿Cuál es su precio esperado?",
          "bid Now": "haga su oferta",
          "Post your truck and get loads": "Publica tu camión y recibe cargas",
          "Find Loads": "encontrar cargas",
          "Attach Lorry": "Adjuntar camión",
          "Near Load": "Cerca de la carga",
          "Code": "Código",
          "Already have an account?  ": "¿Ya tienes una cuenta?",
          "Mobile Number": "Número de teléfono móvil",
          "If A Match is Found, The System Sends An Mobile To The User's Registered Mobile Number With Instructions For Resetting Their Password.":
              "Si se encuentra una coincidencia, el sistema envía un teléfono móvil al número de móvil registrado del usuario con instrucciones para restablecer su contraseña.",
          "Forgot Password": "Has olvidado tu contraseña",
          "Find Lorry": "encontrar camión",
          "Post Loads": "Publicar cargas",
          "Faq": "Preguntas más frecuentes",
          "Continue With Wallet": "Continuar con billetera",
          "Wallet information": "Información de billetera",
          "Enter your Price": "Introduce tu precio",
          "Bid Now": "Haga su oferta",
          "FAQ": "Preguntas más frecuentes",
          "Reject": "Rechazar",
          "offer": "oferta",
          "Load Tracking Status": "Estado de seguimiento de carga",
          "Accept & Pay": "Aceptar y pagar",
          "Lorry Owner Response": "Respuesta del propietario del camión",
          "Load": "Carga",
          "Info": "Información",
          "Total Review": "Revisión total",
          "Date of Joining": "Fecha de inscripción",
          "Route Operation": "Operación de ruta",
          "Enter your Feedback": "Ingrese sus comentarios",
          "Transaction ID": "ID de transacción",
          "Payment Gateway": "Pasarela de pago",
          "Payment Information": "Información del pago",
          "Bidder information": "Información del postor",
          "Bid Response": "Respuesta a la oferta",
          "Total Payment": "Pago total",
          "Sub Total": "Subtotal",
          "Payment Method": "Método de pago",
          "ACCEPT & PAY": "ACEPTAR Y PAGAR",
          "Description": "Descripción",
          "Bid Details": "Detalles de la oferta",
          "No": "No",
          "Yes,Continue": "si, continuar",
          "if you delete this bid you would not be able to view or bid on this load":
              "Si elimina esta oferta, no podrá ver ni ofertar por esta carga.",
          "Are you want to delete bid?": "¿Quieres eliminar la oferta?",
          "Your required to contact the lorry owner for further communication":
              "Es necesario que se comunique con el propietario del camión para comunicarse más.",
          "Material": "Material",
          "Load Process": "Proceso de carga",
          "Tonnes": "Toneladas",
          "Date": "Fecha",
          "Shortly You get revert !!": "¡¡Pronto volverás !!",
          "Name": "Nombre",
          "Request sent to Lorry Owner !":
              "¡Solicitud enviada al propietario del camión!",
          "Load Details": "Detalles de carga",
          "Load Posted !": "Cargar ¡Publicado!",
          "Shortly You get leads !!": "¡Pronto obtendrás clientes potenciales!",
          "Drop Contact Details": "Dejar detalles de contacto",
          "Pickup Contact Detail": "Detalles de contacto de recogida",
          "Hours": "Horas",
          "Number of hours": "Número de horas",
          "Not Fix": "No arreglar",
          "The number of hours visible load?":
              "¿El número de horas de carga visible?",
          "What’s your expected price?": "¿Cuál es su precio esperado?",
          "Post": "Correo",
          "Amount": "Cantidad",
          "Per Tonnes": "Por toneladas",
          "Fix": "Arreglar",
          "Select Vehicle": "Seleccionar vehículo",
          "Drop Point": "Punto de entrega",
          "Pickup Point": "Punto de recogida",
          "Next": "Próximo",
          "Number of Tonnes": "Número de toneladas",
          "Material Name": "Nombre del material",
          "Vehicle Type": "tipo de vehiculo",
          "Enter Amount": "Ingrese el monto",
          "Operating Routes": "Rutas operativas",
          "Please verify your identity First":
              "Por favor verifique su identidad primero",
          "Become world’s Transporter":
              "Conviértete en el transportador del mundo",
          "Hello..": "Hola..",
          "Confirm": "Confirmar",
          "Select Payment Gateway": "Seleccione Pasarela de Pago",
          "You haven't made any transaction using wallet yet":
              "Aún no has realizado ninguna transacción usando tu billetera",
          "E-Wallet": "Monedero electrónico",
          "Transaction History": "Historial de transacciones",
          "Total Earning": "Ganancia total",
          "Home": "Hogar",
          "Wallet": "Billetera",
          "Review": "Revisar",
          "Terms & Conditions": "Términos y condiciones",
          "Privacy Policy": "política de privacidad",
          "Refer to Friends": "Referirse a amigos",
          "Profile": "Perfil",
          "Contact Us": "Contáctenos",
          "Language": "Idioma",
          "LogOut": "Cerrar sesión",
          "My Loads": "mis cargas",
          "Booked Lorries": "Camiones reservados",
          "Enter new Password": "Ingrese nueva clave",
          "Submit": "Entregar",
          "No Load Placed! Currently You Don't Have Any Loads":
              "¡Sin carga colocada! Actualmente no tienes ninguna carga",
          "COMPLETED": "TERMINADO",
          "MY CURRENT LOADS": "MIS CARGAS ACTUALES",
          "Booked Loads": "Cargas reservadas",
          "Full Name": "Nombre completo",
          "Email Address": "Dirección de correo electrónico",
          "Seems you are new here, Let’s set up your profile.":
              "Parece que eres nuevo aquí, configuremos tu perfil.",
          "Getting Started!": "¡Empezando!",
          "Verify Account": "Verificar Cuenta",
          "Forgot Password?": "¿Has olvidado tu contraseña?",
          "Sign up": "Inscribirse",
          "Resend code?": "¿Reenviar codigo?",
          "OTP Verification": "Verificación OTP",
          "Please, enter the verification code we send to your mobile ":
              "Por favor, introduce el código de verificación que te enviamos a tu móvil",
          "Login": "Acceso",
          "Forgot  Password?": "¿Has olvidado tu contraseña?",
          "Let’s login for explore continues":
              "Iniciemos sesión para explorar continúa",
          "Welcome Back!": "¡Bienvenido de nuevo!",
          "Get better rates on every deal.":
              "Obtenga mejores tarifas en cada oferta.",
          "The right load for the right truck.":
              "La carga adecuada para el camión adecuado.",
          "Search active loads by location and equipment type":
              "Buscar cargas activas por ubicación y tipo de equipo",
          "We match the right load to the right truck at the right price":
              "Combinamos la carga adecuada con el camión adecuado al precio adecuado",
          "We offer a wide range of problem-solving products designed to help you ship more freight faster":
              "Ofrecemos una amplia gama de productos de resolución de problemas diseñados para ayudarle a enviar más carga más rápido",
        },
        'hi_IN': {
          "Verify" : "सत्यापित करें",
          "Indentity" : "इंडेंटिटी",
          "Now we need to verify your identity" : "अब हमें आपकी पहचान सत्यापित करने की आवश्यकता है",
          "Note" : "टिप्पणी",
          "You are required to must upload both documents after the submit button appeared" : "सबमिट बटन दिखाई देने के बाद आपको दोनों दस्तावेज़ अपलोड करने होंगे",
          "Document Max 1 Picture Selected From Camera" : "दस्तावेज़ अधिकतम 1 चित्र कैमरे से चयनित",
          "Document Max 2 Picture Selected From Gallery" : "गैलरी से चयनित दस्तावेज़ मैक्स 2 चित्र",
          "Document Max 3 Picture Selected" : "दस्तावेज़ अधिकतम 3 चित्र चयनित",
          "Take a Passport or ID to Check Your Information(Upload at Least 2 document)" : "अपनी जानकारी जांचने के लिए पासपोर्ट या आईडी लें (कम से कम 2 दस्तावेज़ अपलोड करें)",
          "Passport Scan" : "पासपोर्ट स्कैन",
          "Haven't uploaded yet" : "अभी तक अपलोड नहीं किया है",
          "Submit All" : "सभी को प्रस्तुत करें",
          "Selfie with your front camera to verify your identity" : "अपनी पहचान सत्यापित करने के लिए अपने फ्रंट कैमरे से सेल्फी लें",
          "Selfie" : "सेल्फी",
          "UPI" : "है मैं",
          "Bank name" : "बैंक का नाम",
          "Account number" : "खाता संख्या",
          "Account holder name" : "खाता धारक का नाम",
          "Account IFSC" : "खाता आईएफएससी",
          "Paypal" : "Paypal",
          "Withdraw Limit" : "सीमा वापस लें",
          "Cancle" : "कैंसिल",
          "Proceed" : "आगे बढ़ना",
          "Routes" : "मार्गों",
          "Rc Verified" : "आरसी सत्यापित",
          "Drop" : "बूँद",
          "PickUp" : "उठाना",
          "FIND_LORRY" : "FIND_LORRY",
          "Rate to" : "को रेट करें",
          "Loads" : "भार",
          "Load Owner Response" : "स्वामी प्रतिक्रिया लोड करें",
          "Payable Amount" : "देय राशि",
          "Accept" : "स्वीकार करना",
          "Send offer" : "प्रस्ताव भेजें",
          "Waiting for offer Response" : "प्रस्ताव प्रतिक्रिया की प्रतीक्षा में",
          "UnLoad" : "उतारना",
          "Enter Your Location" : "अपनी स्थिति दर्ज़ करें",
          "Select Vehicle type for your load" : "अपने भार के लिए वाहन का प्रकार चुनें",
          "Available" : "उपलब्ध",
          "Rejected" : "अस्वीकार कर दिया",
          "Search" : "खोज",
          "Immediately Available" : "तुरंत उपलब्ध",
          "Select your lorry" : "अपनी लॉरी चुनें",
          "Enter Bid Amount" : "बोली राशि दर्ज करें",
          "Bid" : "बोली",
          "Select Routes" : "रूट चुनें",
          "Select All" : "सबका चयन करें",
          "Upload lorry document (Required at least 2 document)" : "लॉरी दस्तावेज़ अपलोड करें (कम से कम 2 दस्तावेज़ आवश्यक हैं)",
          "Lorry Document" : "लॉरी दस्तावेज़",
          "Enter Required lorry Document" : "आवश्यक लॉरी दस्तावेज़ दर्ज करें",
          "Simplify the way you find carriers.":
              "वाहक ढूंढने का तरीका सरल बनाएं.",
          "Don’t have an account?  ": "कोई खाता नहीं है?",
          "Password": "पासवर्ड",
          "Uip": "यूआईपी",
          "Pay by": "द्वारा भुगतान",
          "Request Date": "अनुरोध की तिथि",
          "Proof": "सबूत",
          "My Lorry's": "मेरी लॉरी",
          "Payout Id": "भुगतान आईडी",
          "paypal": "Paypal",
          "bank transfer": "बैंक ट्रांसफर",
          "Payout Request": "भुगतान अनुरोध",
          "Enter your amount": "अपनी राशि दर्ज करें",
          "Request": "अनुरोध",
          "Earning": "कमाई",
          "You required to contact the lorry owner for further communication":
              "आगे की बातचीत के लिए आपको लॉरी मालिक से संपर्क करना होगा",
          "Cancellation Policy": "रद्द करने की नीति",
          "Contact Details": "सम्पर्क करने का विवरण",
          "Enter Lorry Number": "लॉरी नंबर दर्ज करें",
          "Transport Information": "परिवहन सूचना",
          "Skip": "छोडना",
          "Add Lorry": "लॉरी जोड़ें",
          "Availability Status": "उपलब्धता स्थिति",
          "What's your expected price?": "आपकी अपेक्षित कीमत क्या है?",
          "bid Now": "बोली लगाओ",
          "Post your truck and get loads":
              "अपना ट्रक पोस्ट करें और सामान प्राप्त करें",
          "Find Loads": "भार खोजें",
          "Attach Lorry": "लॉरी संलग्न करें",
          "Near Load": "लोड के पास",
          "Code": "कोड",
          "Already have an account?  ":
              "क्या आपके पास पहले से एक खाता मौजूद है?",
          "Mobile Number": "मोबाइल नंबर",
          "If A Match is Found, The System Sends An Mobile To The User's Registered Mobile Number With Instructions For Resetting Their Password.":
              "यदि कोई मिलान पाया जाता है, तो सिस्टम उपयोगकर्ता के पंजीकृत मोबाइल नंबर पर उनका पासवर्ड रीसेट करने के निर्देश के साथ एक मोबाइल भेजता है।",
          "Forgot Password": "पासवर्ड भूल गए",
          "Find Lorry": "लॉरी ढूंढो",
          "Post Loads": "पोस्ट लोड",
          "Faq": "सामान्य प्रश्न",
          "Continue With Wallet": "वॉलेट के साथ जारी रखें",
          "Wallet information": "बटुए की जानकारी",
          "Enter your Price": "अपनी कीमत दर्ज करें",
          "Bid Now": "बोली लगाओ",
          "FAQ": "सामान्य प्रश्न",
          "Reject": "अस्वीकार करना",
          "offer": "प्रस्ताव",
          "Load Tracking Status": "ट्रैकिंग स्थिति लोड करें",
          "Accept & Pay": "स्वीकार करें और भुगतान करें",
          "Lorry Owner Response": "लॉरी मालिक की प्रतिक्रिया",
          "Load": "भार",
          "Info": "जानकारी",
          "Total Review": "कुल समीक्षा",
          "Date of Joining": "शामिल होने की तिथि",
          "Route Operation": "मार्ग संचालन",
          "Enter your Feedback": "अपनी प्रतिक्रिया दर्ज करें",
          "Transaction ID": "लेन-देन आईडी",
          "Payment Gateway": "भुगतान गेटवे",
          "Payment Information": "भुगतान जानकारी",
          "Bidder information": "बोली लगाने वाले की जानकारी",
          "Bid Response": "बोली प्रतिक्रिया",
          "Total Payment": "कुल भुगतान",
          "Sub Total": "उप योग",
          "Payment Method": "भुगतान विधि",
          "ACCEPT & PAY": "स्वीकार करें और भुगतान करें",
          "Description": "विवरण",
          "Bid Details": "बोली विवरण",
          "No": "नहीं",
          "Yes,Continue": "हाँ, जारी रखें",
          "if you delete this bid you would not be able to view or bid on this load":
              "यदि आप इस बोली को हटा देते हैं तो आप इस लोड को देख या बोली नहीं लगा पाएंगे",
          "Are you want to delete bid?": "क्या आप बोली हटाना चाहते हैं?",
          "Your required to contact the lorry owner for further communication":
              "आगे की बातचीत के लिए आपको लॉरी मालिक से संपर्क करना होगा",
          "Material": "सामग्री",
          "Load Process": "लोड प्रक्रिया",
          "Tonnes": "टन",
          "Date": "तारीख",
          "Shortly You get revert !!": "जल्द ही आपको उत्तर मिलेगा!!",
          "Name": "नाम",
          "Request sent to Lorry Owner !": "लॉरी मालिक को अनुरोध भेजा गया!",
          "Load Details": "विवरण लोड करें",
          "Load Posted !": "लोड पोस्ट किया गया!",
          "Shortly You get leads !!": "जल्द ही आपको लीड मिल जाएगी!!",
          "Drop Contact Details": "संपर्क विवरण छोड़ें",
          "Pickup Contact Detail": "पिकअप संपर्क विवरण",
          "Hours": "घंटे",
          "Number of hours": "घंटों की संख्या",
          "Not Fix": "तय नहीं",
          "The number of hours visible load?": "दृश्यमान लोड घंटों की संख्या?",
          "What’s your expected price?": "आपकी अपेक्षित कीमत क्या है?",
          "Post": "डाक",
          "Amount": "मात्रा",
          "Per Tonnes": "प्रति टन",
          "Fix": "हल करना",
          "Select Vehicle": "वाहन चुनें",
          "Drop Point": "ड्रॉप बिंदु",
          "Pickup Point": "पिक अप बिंदु",
          "Next": "अगला",
          "Number of Tonnes": "टन की संख्या",
          "Material Name": "सामग्री नाम",
          "Vehicle Type": "वाहन का प्रकार",
          "Enter Amount": "राशि डालें",
          "Operating Routes": "परिचालन मार्ग",
          "Please verify your identity First":
              "कृपया पहले अपनी पहचान सत्यापित करें",
          "Become world’s Transporter": "दुनिया के ट्रांसपोर्टर बनें",
          "Hello..": "नमस्ते..",
          "Confirm": "पुष्टि करना",
          "Select Payment Gateway": "पेमेंट गेटवे चुनें",
          "You haven't made any transaction using wallet yet":
              "आपने अभी तक वॉलेट का उपयोग करके कोई लेनदेन नहीं किया है",
          "E-Wallet": "ई-बटुआ",
          "Transaction History": "ट्रांजेक्शन इतिहास",
          "Total Earning": "कुल कमाई",
          "Home": "घर",
          "Wallet": "बटुआ",
          "Review": "समीक्षा",
          "Terms & Conditions": "नियम एवं शर्तें",
          "Privacy Policy": "गोपनीयता नीति",
          "Refer to Friends": "मित्रों का संदर्भ लें",
          "Profile": "प्रोफ़ाइल",
          "Contact Us": "संपर्क करें",
          "Language": "भाषा",
          "LogOut": "लॉग आउट",
          "My Loads": "मेरा भार",
          "Booked Lorries": "लॉरीज़ बुक की गईं",
          "Enter new Password": "नया पासवर्ड दर्ज करें",
          "Submit": "जमा करना",
          "No Load Placed! Currently You Don't Have Any Loads":
              "कोई भार नहीं डाला गया! वर्तमान में आपके पास कोई भार नहीं है",
          "COMPLETED": "पुरा होना",
          "MY CURRENT LOADS": "मेरा वर्तमान भार",
          "Booked Loads": "बहुत सारा सामान बुक किया गया",
          "Full Name": "पूरा नाम",
          "Email Address": "मेल पता",
          "Seems you are new here, Let’s set up your profile.":
              "लगता है आप यहां नए हैं, चलिए आपकी प्रोफ़ाइल सेट करते हैं।",
          "Getting Started!": "शुरू करना!",
          "Verify Account": "खाता सत्यापित करें",
          "Forgot Password?": "पासवर्ड भूल गए?",
          "Sign up": "साइन अप करें",
          "Resend code?": "पुन: कोड भेजे?",
          "OTP Verification": "ओटीपी सत्यापन",
          "Please, enter the verification code we send to your mobile ":
              "कृपया, हमारे द्वारा आपके मोबाइल पर भेजा गया सत्यापन कोड दर्ज करें",
          "Login": "लॉग इन करें",
          "Forgot  Password?": "पासवर्ड भूल गए?",
          "Let’s login for explore continues":
              "आइए अन्वेषण जारी रखने के लिए लॉगिन करें",
          "Welcome Back!": "वापसी पर स्वागत है!",
          "Get better rates on every deal.":
              "प्रत्येक सौदे पर बेहतर दरें प्राप्त करें।",
          "The right load for the right truck.": "सही ट्रक के लिए सही लोड.",
          "Search active loads by location and equipment type":
              "स्थान और उपकरण प्रकार के आधार पर सक्रिय लोड खोजें",
          "We match the right load to the right truck at the right price":
              "हम सही कीमत पर सही ट्रक से सही लोड का मिलान करते हैं",
          "We offer a wide range of problem-solving products designed to help you ship more freight faster":
              "हम आपको अधिक माल तेजी से भेजने में मदद करने के लिए डिज़ाइन किए गए समस्या-समाधान उत्पादों की एक विस्तृत श्रृंखला पेश करते हैं",
        },
        'ge_In': {
          "Verify" : "ચકાસો",
          "Indentity" : "ઓળખાણ",
          "Now we need to verify your identity" : "હવે અમારે તમારી ઓળખ ચકાસવાની જરૂર છે",
          "Note" : "નોંધ",
          "You are required to must upload both documents after the submit button appeared" : "સબમિટ બટન દેખાય તે પછી તમારે બંને દસ્તાવેજો અપલોડ કરવા આવશ્યક છે",
          "Document Max 1 Picture Selected From Camera" : "દસ્તાવેજ મહત્તમ 1 ચિત્ર કેમેરામાંથી પસંદ કરેલ",
          "Document Max 2 Picture Selected From Gallery" : "દસ્તાવેજ મેક્સ 2 ચિત્ર ગેલેરીમાંથી પસંદ કરેલ",
          "Document Max 3 Picture Selected" : "દસ્તાવેજ મહત્તમ 3 ચિત્ર પસંદ કર્યું",
          "Take a Passport or ID to Check Your Information(Upload at Least 2 document)" : "તમારી માહિતી તપાસવા માટે પાસપોર્ટ અથવા ID લો (ઓછામાં ઓછા 2 દસ્તાવેજ અપલોડ કરો)",
          "Passport Scan" : "પાસપોર્ટ સ્કેન",
          "Haven't uploaded yet" : "હજુ સુધી અપલોડ કર્યું નથી",
          "Submit All" : "બધા સબમિટ કરો",
          "Selfie with your front camera to verify your identity" : "તમારી ઓળખ ચકાસવા માટે તમારા ફ્રન્ટ કેમેરા વડે સેલ્ફી લો",
          "Selfie" : "સેલ્ફી",
          "UPI" : "UPI",
          "Bank name" : "બેંકનું નામ",
          "Account number" : "એકાઉન્ટ નંબર",
          "Account holder name" : "ખાતા ધારકનું નામ",
          "Account IFSC" : "IFSC એકાઉન્ટ",
          "Paypal" : "પેપલ",
          "Withdraw Limit" : "ઉપાડ મર્યાદા",
          "Cancle" : "Cancle",
          "Proceed" : "આગળ વધો",
          "Routes" : "માર્ગો",
          "Rc Verified" : "આરસી વેરિફાઈડ",
          "Drop" : "છોડો",
          "PickUp" : "પિકઅપ",
          "FIND_LORRY" : "FIND_LORRY",
          "Rate to" : "માટે દર",
          "Loads" : "લોડ્સ",
          "Load Owner Response" : "લોડ માલિક પ્રતિસાદ",
          "Payable Amount" : "ચૂકવવાપાત્ર રકમ",
          "Accept" : "સ્વીકારો",
          "Send offer" : "ઓફર મોકલો",
          "Waiting for offer Response" : "ઑફર પ્રતિસાદની રાહ જોઈ રહ્યાં છીએ",
          "UnLoad" : "અનલોડ કરો",
          "Enter Your Location" : "તમારું સ્થાન દાખલ કરો",
          "Select Vehicle type for your load" : "તમારા લોડ માટે વાહનનો પ્રકાર પસંદ કરો",
          "Available" : "ઉપલબ્ધ છે",
          "Rejected" : "ફગાવી દીધી",
          "Search" : "શોધો",
          "Immediately Available" : "તરત જ ઉપલબ્ધ",
          "Select your lorry" : "તમારી લારી પસંદ કરો",
          "Enter Bid Amount" : "બિડની રકમ દાખલ કરો",
          "Bid" : "બોલી",
          "Select Routes" : "રૂટ્સ પસંદ કરો",
          "Select All" : "બધા પસંદ કરો",
          "Upload lorry document (Required at least 2 document)" : "લોરી દસ્તાવેજ અપલોડ કરો (ઓછામાં ઓછા 2 દસ્તાવેજ જરૂરી)",
          "Lorry Document" : "લોરી દસ્તાવેજ",
          "Enter Required lorry Document" : "જરૂરી લોરી દસ્તાવેજ દાખલ કરો",
          "Simplify the way you find carriers.": "તમને કેરિયર્સ શોધવાની રીતને સરળ બનાવો.",
          "Don’t have an account?  ": "ખાતું નથી?",
          "Password": "પાસવર્ડ",
          "Uip": "uip",
          "Pay by": "દ્વારા ચૂકવણી કરો",
          "Request Date": "વિનંતી તારીખ",
          "Proof": "પુરાવો",
          "My Lorry's": "મારી લોરીની",
          "Payout Id": "ચુકવણી ID",
          "paypal": "પેપલ",
          "bank transfer": "બેન્ક ટ્રાન્સફર",
          "Payout Request": "ચૂકવણીની વિનંતી",
          "Enter your amount": "તમારી રકમ દાખલ કરો",
          "Request": "વિનંતી",
          "Earning": "આવક",
          "You required to contact the lorry owner for further communication":
              "તમારે વધુ સંદેશાવ્યવહાર માટે લોરી માલિકનો સંપર્ક કરવો જરૂરી છે",
          "Cancellation Policy": "રદીકરણ નીતિ",
          "Contact Details": "સંપર્ક વિગતો",
          "Enter Lorry Number": "લોરી નંબર દાખલ કરો",
          "Transport Information": "પરિવહન માહિતી",
          "Skip": "અવગણો",
          "Add Lorry": "લોરી ઉમેરો",
          "Availability Status": "ઉપલબ્ધતા સ્થિતિ",
          "What's your expected price?": "તમારી અપેક્ષિત કિંમત શું છે?",
          "bid Now": "હવે બોલી",
          "Post your truck and get loads": "તમારી ટ્રક પોસ્ટ કરો અને લોડ મેળવો",
          "Find Loads": "લોડ્સ શોધો",
          "Attach Lorry": "લારી જોડો",
          "Near Load": "લોડની નજીક",
          "Code": "કોડ",
          "Already have an account?  ": "પહેલેથી જ એકાઉન્ટ છે?",
          "Mobile Number": "મોબાઇલ નંબર",
          "If A Match is Found, The System Sends An Mobile To The User's Registered Mobile Number With Instructions For Resetting Their Password.":
              "જો મેચ જોવા મળે છે, તો સિસ્ટમ વપરાશકર્તાના રજિસ્ટર્ડ મોબાઈલ નંબર પર તેમનો પાસવર્ડ રીસેટ કરવા માટેની સૂચનાઓ સાથે મોબાઈલ મોકલે છે.",
          "Forgot Password": "પાસવર્ડ ભૂલી ગયા છો",
          "Find Lorry": "લોરી શોધો",
          "Post Loads": "પોસ્ટ લોડ્સ",
          "Faq": "FAQ",
          "Continue With Wallet": "વૉલેટ સાથે ચાલુ રાખો",
          "Wallet information": "વૉલેટ માહિતી",
          "Enter your Price": "તમારી કિંમત દાખલ કરો",
          "Bid Now": "હવે બિડ કરો",
          "FAQ": "FAQ",
          "Reject": "અસ્વીકાર",
          "offer": "ઓફર",
          "Load Tracking Status": "લોડ ટ્રેકિંગ સ્થિતિ",
          "Accept & Pay": "સ્વીકારો અને ચૂકવો",
          "Lorry Owner Response": "લોરી માલિક પ્રતિભાવ",
          "Load": "ભાર",
          "Info": "માહિતી",
          "Total Review": "કુલ સમીક્ષા",
          "Date of Joining": "જોડાવાની તારીખ",
          "Route Operation": "રૂટ ઓપરેશન",
          "Enter your Feedback": "તમારો પ્રતિસાદ દાખલ કરો",
          "Transaction ID": "ટ્રાન્ઝેક્શન આઈડી",
          "Payment Gateway": "પેમેન્ટ ગેટવે",
          "Payment Information": "ચુકવણી માહિતી",
          "Bidder information": "બિડર માહિતી",
          "Bid Response": "બિડ પ્રતિસાદ",
          "Total Payment": "કુલ ચુકવણી",
          "Sub Total": "પેટા કુલ",
          "Payment Method": "ચુકવણી પદ્ધતિ",
          "ACCEPT & PAY": "સ્વીકારો અને ચૂકવો",
          "Description": "વર્ણન",
          "Bid Details": "બિડ વિગતો",
          "No": "ના",
          "Yes,Continue": "હા, ચાલુ રાખો",
          "if you delete this bid you would not be able to view or bid on this load":
              "જો તમે આ બિડ કાઢી નાખો છો, તો તમે આ લોડને જોઈ કે બિડ કરી શકશો નહીં",
          "Are you want to delete bid?": "શું તમે બિડ કાઢી નાખવા માંગો છો?",
          "Your required to contact the lorry owner for further communication":
              "વધુ સંચાર માટે તમારે લોરી માલિકનો સંપર્ક કરવો જરૂરી છે",
          "Material": "સામગ્રી",
          "Load Process": "લોડ પ્રક્રિયા",
          "Tonnes": "ટોન",
          "Date": "તારીખ",
          "Shortly You get revert !!": "ટૂંક સમયમાં તમે પાછા ફરો !!",
          "Name": "નામ",
          "Request sent to Lorry Owner !": "લોરીના માલિકને વિનંતી મોકલી!",
          "Load Details": "લોડ વિગતો",
          "Load Posted !": "લોડ પોસ્ટ કર્યું!",
          "Shortly You get leads !!": "ટૂંક સમયમાં તમને લીડ્સ મળશે!!",
          "Drop Contact Details": "સંપર્ક વિગતો મૂકો",
          "Pickup Contact Detail": "પિકઅપ સંપર્ક વિગતો",
          "Hours": "કલાક",
          "Number of hours": "કલાકોની સંખ્યા",
          "Not Fix": "સ્થિર નથી",
          "The number of hours visible load?": "દૃશ્યમાન લોડના કલાકોની સંખ્યા?",
          "What’s your expected price?": "તમારી અપેક્ષિત કિંમત શું છે?",
          "Post": "પોસ્ટ્સ",
          "Amount": "રકમ",
          "Per Tonnes": "પ્રતિ ટન",
          "Fix": "નિશ્ચિત",
          "Select Vehicle": "વાહન પસંદ કરો",
          "Drop Point": "ડ્રોપ પોઈન્ટ",
          "Pickup Point": "પિકઅપ પોઈન્ટ",
          "Next": "આગળ",
          "Number of Tonnes": "ટનની સંખ્યા",
          "Material Name": "સામગ્રીનું નામ",
          "Vehicle Type": "વાહનનો પ્રકાર",
          "Enter Amount": "રકમ દાખલ કરો",
          "Operating Routes": "ઓપરેટિંગ રૂટ્સ",
          "Please verify your identity First":
              "કૃપા કરીને પહેલા તમારી ઓળખ ચકાસો",
          "Become world’s Transporter": "વિશ્વના ટ્રાન્સપોર્ટર બનો",
          "Hello..": "નમસ્તે..",
          "Confirm": "પુષ્ટિ કરો",
          "Select Payment Gateway": "પેમેન્ટ ગેટવે પસંદ કરો",
          "You haven't made any transaction using wallet yet":
              "તમે હજી સુધી વૉલેટનો ઉપયોગ કરીને કોઈ વ્યવહાર કર્યો નથી",
          "E-Wallet": "ઇ-વોલેટ",
          "Transaction History": "વ્યવહાર ઇતિહાસ",
          "Total Earning": "કુલ કમાણી",
          "Home": "ઘર",
          "Wallet": "વૉલેટ",
          "Review": "સમીક્ષાઓ",
          "Terms & Conditions": "શરતો અને નિયમો",
          "Privacy Policy": "ગોપનીયતા નીતિ",
          "Refer to Friends": "મિત્રો નો સંદર્ભ લો",
          "Profile": "પ્રોફાઇલ",
          "Contact Us": "અમારો સંપર્ક કરો",
          "Language": "ભાષા",
          "LogOut": "લૉગ આઉટ",
          "My Loads": "મારા લોડ્સ",
          "Booked Lorries": "લોરીઓ બુક કરાવી",
          "Enter new Password": "નવો પાસવર્ડ દાખલ કરો",
          "Submit": "સબમિટ કરો",
          "No Load Placed! Currently You Don't Have Any Loads":
              "કોઈ લોડ મૂકવામાં આવ્યું નથી! હાલમાં તમારી પાસે કોઈ ભાર નથી",
          "COMPLETED": "પૂર્ણ થયું",
          "MY CURRENT LOADS": "મારા વર્તમાન લોડ્સ",
          "Booked Loads": "બુક કરાવેલ લોડ",
          "Full Name": "પૂરું નામ",
          "Email Address": "ઈ - મેઈલ સરનામું",
          "Seems you are new here, Let’s set up your profile.":
              "લાગે છે કે તમે અહીં નવા છો, ચાલો તમારી પ્રોફાઇલ સેટ કરીએ.",
          "Getting Started!": "પ્રારંભ કરો!",
          "Verify Account": "એકાઉન્ટ ચકાસો",
          "Forgot Password?": "પાસવર્ડ ભૂલી ગયા છો?",
          "Sign up": "સાઇન અપ કરો",
          "Resend code?": "કોડ ફરીથી મોકલીએ?",
          "OTP Verification": "OTP ચકાસણી",
          "Please, enter the verification code we send to your mobile ":
              "કૃપા કરીને, અમે તમારા મોબાઇલ પર મોકલીએ છીએ તે ચકાસણી કોડ દાખલ કરો",
          "Login": "પ્રવેશ કરો",
          "Forgot  Password?": "પાસવર્ડ ભૂલી ગયા છો?",
          "Let’s login for explore continues":
              "ચાલો અન્વેષણ ચાલુ રાખવા માટે લૉગિન કરીએ",
          "Welcome Back!": "ફરી સ્વાગત છે!",
          "Get better rates on every deal.": "દરેક સોદા પર વધુ સારા દરો મેળવો.",
          "The right load for the right truck.": "જમણી ટ્રક માટે યોગ્ય લોડ.",
          "Search active loads by location and equipment type":
              "સ્થાન અને સાધનોના પ્રકાર દ્વારા સક્રિય લોડ શોધો",
          "We match the right load to the right truck at the right price":
              "અમે યોગ્ય કિંમતે યોગ્ય ટ્રક સાથે યોગ્ય ભારને મેચ કરીએ છીએ",
          "We offer a wide range of problem-solving products designed to help you ship more freight faster":
              "અમે તમને વધુ નૂર ઝડપથી મોકલવામાં મદદ કરવા માટે રચાયેલ સમસ્યા-નિરાકરણ ઉત્પાદનોની વિશાળ શ્રેણી ઑફર કરીએ છીએ",
        },
        'Id_Ge': {
          "Verify" : "Memeriksa",
          "Indentity" : "Identitas",
          "Now we need to verify your identity" : "Sekarang kami perlu memverifikasi identitas Anda",
          "Note" : "Catatan",
          "You are required to must upload both documents after the submit button appeared" : "Anda diharuskan mengunggah kedua dokumen tersebut setelah tombol kirim muncul",
          "Document Max 1 Picture Selected From Camera" : "Dokumen Maks 1 Gambar Dipilih Dari Kamera",
          "Document Max 2 Picture Selected From Gallery" : "Dokumen Maks 2 Gambar Dipilih Dari Galeri",
          "Document Max 3 Picture Selected" : "Dokumen Maks 3 Gambar Dipilih",
          "Take a Passport or ID to Check Your Information(Upload at Least 2 document)" : "Ambil Paspor atau ID untuk Memeriksa Informasi Anda (Unggah Minimal 2 dokumen)",
          "Passport Scan" : "Pemindaian Paspor",
          "Haven't uploaded yet" : "Belum diunggah",
          "Submit All" : "Kirim Semua",
          "Selfie with your front camera to verify your identity" : "Selfie dengan kamera depan Anda untuk memverifikasi identitas Anda",
          "Selfie" : "Selfie",
          "UPI" : "UPI",
          "Bank name" : "Nama bank",
          "Account number" : "Nomor rekening",
          "Account holder name" : "Nama pemegang rekening",
          "Account IFSC" : "Akun IFSC",
          "Paypal" : "Paypal",
          "Withdraw Limit" : "Batas Penarikan",
          "Cancle" : "Pembatalan",
          "Proceed" : "Melanjutkan",
          "Routes" : "Rute",
          "Rc Verified" : "RC Terverifikasi",
          "Drop" : "Menjatuhkan",
          "PickUp" : "Menjemput",
          "FIND_LORRY" : "TEMUKAN_LORRY",
          "Rate to" : "Beri nilai ke",
          "Loads" : "Banyak",
          "Load Owner Response" : "Respon Pemilik Muat",
          "Payable Amount" : "Jumlah Hutang",
          "Accept" : "Menerima",
          "Send offer" : "Kirim penawaran",
          "Waiting for offer Response" : "Menunggu tawaran Respon",
          "UnLoad" : "Membongkar",
          "Enter Your Location" : "Masukkan Lokasi Anda",
          "Select Vehicle type for your load" : "Pilih jenis Kendaraan untuk muatan Anda",
          "Available" : "Tersedia",
          "Rejected" : "Ditolak",
          "Search" : "Mencari",
          "Immediately Available" : "Segera Tersedia",
          "Select your lorry" : "Pilih truk Anda",
          "Enter Bid Amount" : "Masukkan Jumlah Tawaran",
          "Bid" : "Penawaran",
          "Select Routes" : "Pilih Rute",
          "Select All" : "Pilih Semua",
          "Upload lorry document (Required at least 2 document)" : "Unggah dokumen truk (Diperlukan minimal 2 dokumen)",
          "Lorry Document" : "Dokumen Truk",
          "Enter Required lorry Document" : "Masukkan Dokumen truk yang Diperlukan",
          "Simplify the way you find carriers.": "Sederhanakan cara Anda menemukan operator.",
          "Don’t have an account?  ": "Belum punya akun?",
          "Password": "Kata sandi",
          "Uip": "uip",
          "Pay by": "Membayar dengan",
          "Request Date": "Tanggal Permintaan",
          "Proof": "Bukti",
          "My Lorry's": "trukku",
          "Payout Id": "ID pembayaran",
          "paypal": "paypal",
          "bank transfer": "transfer Bank",
          "Payout Request": "Permintaan Pembayaran",
          "Enter your amount": "Masukkan jumlah Anda",
          "Request": "meminta",
          "Earning": "Penghasilan",
          "You required to contact the lorry owner for further communication":
              "Anda perlu menghubungi pemilik truk untuk komunikasi lebih lanjut",
          "Cancellation Policy": "Kebijakan Pembatalan",
          "Contact Details": "Detail Kontak",
          "Enter Lorry Number": "Masukkan Nomor Truk",
          "Transport Information": "Informasi Transportasi",
          "Skip": "melewati",
          "Add Lorry": "Tambahkan truk",
          "Availability Status": "Status Ketersediaan",
          "What's your expected price?": "Berapa harga yang Anda harapkan?",
          "bid Now": "tawar sekarang",
          "Post your truck and get loads":
              "Posting truk Anda dan dapatkan muatan",
          "Find Loads": "Temukan Banyak",
          "Attach Lorry": "Pasang Truk",
          "Near Load": "Dekat Beban",
          "Code": "kode",
          "Already have an account?  ": "Sudah memiliki akun?",
          "Mobile Number": "Nomor handphone",
          "If A Match is Found, The System Sends An Mobile To The User's Registered Mobile Number With Instructions For Resetting Their Password.":
              "Jika Ditemukan Kecocokan, Sistem Mengirimkan Ponsel Ke Nomor Ponsel Terdaftar Pengguna Dengan Petunjuk Untuk Mengatur Ulang Kata Sandinya.",
          "Forgot Password": "Tidak ingat kata sandi",
          "Find Lorry": "Temukan truk",
          "Post Loads": "Beban Posting",
          "Faq": "Pertanyaan Umum",
          "Continue With Wallet": "Lanjutkan Dengan Dompet",
          "Wallet information": "Informasi dompet",
          "Enter your Price": "Masukkan Harga Anda",
          "Bid Now": "Tawar sekarang",
          "FAQ": "Pertanyaan Umum",
          "Reject": "menolak",
          "offer": "menawarkan",
          "Load Tracking Status": "Status Pelacakan Beban",
          "Accept & Pay": "Terima & Bayar",
          "Lorry Owner Response": "Tanggapan Pemilik Truk",
          "Load": "memuat",
          "Info": "Informasi",
          "Total Review": "Ulasan Total",
          "Date of Joining": "Tanggal Bergabung",
          "Route Operation": "Operasi Rute",
          "Enter your Feedback": "Masukkan Masukan Anda",
          "Transaction ID": "ID transaksi",
          "Payment Gateway": "Gerbang pembayaran",
          "Payment Information": "Informasi Pembayaran",
          "Bidder information": "Informasi penawar",
          "Bid Response": "Respon Tawaran",
          "Total Payment": "Total pembayaran",
          "Sub Total": "Sub Jumlah",
          "Payment Method": "Cara Pembayaran",
          "ACCEPT & PAY": "TERIMA & BAYAR",
          "Description": "Keterangan",
          "Bid Details": "Detail Tawaran",
          "No": "TIDAK",
          "Yes,Continue": "Ya, Lanjutkan",
          "if you delete this bid you would not be able to view or bid on this load":
              "jika Anda menghapus tawaran ini, Anda tidak akan dapat melihat atau menawar muatan ini",
          "Are you want to delete bid?": "Apakah Anda ingin menghapus tawaran?",
          "Your required to contact the lorry owner for further communication":
              "Anda diharuskan menghubungi pemilik truk untuk komunikasi lebih lanjut",
          "Material": "Bahan",
          "Load Process": "Proses Muat",
          "Tonnes": "nada",
          "Date": "tanggal",
          "Shortly You get revert !!": "Segera Anda kembali!!",
          "Name": "Nama",
          "Request sent to Lorry Owner !":
              "Permintaan dikirim ke Pemilik Lorry!",
          "Load Details": "Memuat Detail",
          "Load Posted !": "Muat Diposting!",
          "Shortly You get leads !!": "Segera Anda mendapatkan petunjuk!!",
          "Drop Contact Details": "Jatuhkan Detail Kontak",
          "Pickup Contact Detail": "Detail Kontak Penjemputan",
          "Hours": "Jam",
          "Number of hours": "Jumlah jam",
          "Not Fix": "Tidak tetap",
          "The number of hours visible load?": "Jumlah jam terlihat memuat?",
          "What’s your expected price?": "Berapa harga yang Anda harapkan?",
          "Post": "Postingan",
          "Amount": "Jumlah",
          "Per Tonnes": "Per Ton",
          "Fix": "tetap",
          "Select Vehicle": "Pilih Kendaraan",
          "Drop Point": "Titik Jatuh",
          "Pickup Point": "Titik Penjemputan",
          "Next": "Berikutnya",
          "Number of Tonnes": "Jumlah Ton",
          "Material Name": "nama material",
          "Vehicle Type": "Jenis Kendaraan",
          "Enter Amount": "Masukan jumlah",
          "Operating Routes": "Rute Operasi",
          "Please verify your identity First":
              "Harap verifikasi identitas Anda terlebih dahulu",
          "Become world’s Transporter": "Menjadi transporter dunia",
          "Hello..": "Halo..",
          "Confirm": "mengonfirmasi",
          "Select Payment Gateway": "Pilih Gerbang Pembayaran",
          "You haven't made any transaction using wallet yet":
              "Anda belum melakukan transaksi apa pun menggunakan dompet",
          "E-Wallet": "Dompet Elektronik",
          "Transaction History": "sejarah transaksi",
          "Total Earning": "Jumlah Penghasilan",
          "Home": "Rumah",
          "Wallet": "dompet",
          "Review": "Ulasan",
          "Terms & Conditions": "Syarat & Ketentuan",
          "Privacy Policy": "Kebijakan pribadi",
          "Refer to Friends": "Rujuk ke Teman",
          "Profile": "Profil",
          "Contact Us": "Hubungi kami",
          "Language": "Bahasa",
          "LogOut": "Keluar",
          "My Loads": "Beban saya",
          "Booked Lorries": "Truk yang dipesan",
          "Enter new Password": "Masukan kata sandi baru",
          "Submit": "Kirim",
          "No Load Placed! Currently You Don't Have Any Loads":
              "Tidak Ada Beban yang Ditempatkan! Saat ini Anda Tidak Memiliki Beban Apa Pun",
          "COMPLETED": "LENGKAP",
          "MY CURRENT LOADS": "BEBAN SAYA SAAT INI",
          "Booked Loads": "Banyak yang Dipesan",
          "Full Name": "Nama lengkap",
          "Email Address": "Alamat email",
          "Seems you are new here, Let’s set up your profile.":
              "Tampaknya Anda baru di sini, Mari siapkan profil Anda.",
          "Getting Started!": "Mulai!",
          "Verify Account": "verifikasi akun",
          "Forgot Password?": "Tidak ingat kata sandi?",
          "Sign up": "Mendaftar",
          "Resend code?": "Kirim ulang kode?",
          "OTP Verification": "Verifikasi OTP",
          "Please, enter the verification code we send to your mobile ":
              "Silakan masukkan kode verifikasi yang kami kirimkan ke ponsel Anda",
          "Login": "Gabung",
          "Forgot  Password?": "Tidak ingat kata sandi?",
          "Let’s login for explore continues":
              "Mari login untuk penjelajahan berlanjut",
          "Welcome Back!": "Selamat Datang kembali!",
          "Get better rates on every deal.":
              "Dapatkan harga yang lebih baik di setiap transaksi.",
          "The right load for the right truck.":
              "Muatan yang tepat untuk truk yang tepat.",
          "Search active loads by location and equipment type":
              "Cari beban aktif berdasarkan lokasi dan jenis peralatan",
          "We match the right load to the right truck at the right price":
              "Kami mencocokkan muatan yang tepat dengan truk yang tepat dengan harga yang tepat",
          "We offer a wide range of problem-solving products designed to help you ship more freight faster":
              "Kami menawarkan beragam produk pemecahan masalah yang dirancang untuk membantu Anda mengirimkan lebih banyak barang dengan lebih cepat",
        }
      };
}
